//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignItRight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignItRight.Properties.LoggingResources", typeof(LoggingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted contact information..
        /// </summary>
        internal static string ContactManager_DeleteContactCompleted {
            get {
                return ResourceManager.GetString("ContactManager_DeleteContactCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not delete contact. {0}.
        /// </summary>
        internal static string ContactManager_DeleteContactFailed {
            get {
                return ResourceManager.GetString("ContactManager_DeleteContactFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Deleteing contact information..
        /// </summary>
        internal static string ContactManager_DeleteContactStarting {
            get {
                return ResourceManager.GetString("ContactManager_DeleteContactStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information loaded..
        /// </summary>
        internal static string ContactManager_LoadContactCompleted {
            get {
                return ResourceManager.GetString("ContactManager_LoadContactCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not load contact. {0}.
        /// </summary>
        internal static string ContactManager_LoadContactFailed {
            get {
                return ResourceManager.GetString("ContactManager_LoadContactFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting loading contact information..
        /// </summary>
        internal static string ContactManager_LoadContactStarting {
            get {
                return ResourceManager.GetString("ContactManager_LoadContactStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact was null..
        /// </summary>
        internal static string ContactManager_LoadFailedContactWasNull {
            get {
                return ResourceManager.GetString("ContactManager_LoadFailedContactWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not save contact. {0}.
        /// </summary>
        internal static string ContactManager_SaveContact_Failed {
            get {
                return ResourceManager.GetString("ContactManager_SaveContact_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information saved..
        /// </summary>
        internal static string ContactManager_SaveContactCompleted {
            get {
                return ResourceManager.GetString("ContactManager_SaveContactCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting saving contact information..
        /// </summary>
        internal static string ContactManager_SaveContactStarting {
            get {
                return ResourceManager.GetString("ContactManager_SaveContactStarting", resourceCulture);
            }
        }
    }
}
